name: Sync with Azure DevOps

on:
  schedule:
    - cron: "*/30 * * * *"
  issues:
    types:
      [
        opened,
        closed,
        deleted,
        reopened,
        edited,
        labeled,
        unlabeled,
        assigned,
        unassigned,
      ]
  issue_comment:
    types: [created]

permissions:
  id-token: write
  issues: write
  contents: read

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync workflow
    steps:
      - uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ENTRA_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.ENTRA_APP_TENANT_ID }}
          allow-no-subscriptions: true
      - name: Get Azure DevOps token
        id: get_ado_token
        run: echo "ado_token=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv)" >> $GITHUB_ENV
      - uses: a11smiles/GitSync@main
        env:
          ado_token: "${{ env.ado_token }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          config_file: "./.github/workflows/sync_config.json"
